version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: DOCKERFILE
    ports:
      - "8020:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]